### ISSUE TITLE
Include certificate authority and scheme like in the rust code?

### ISSUE THREAD

**Issue by AlvinKuruvilla** [AlvinKuruvilla/Sirix-Go#1]
The rust code uses the hyper crate's URI module with Authority and Scheme in the auth.rs file

Maybe the Go Client should also include such things

**Comment by mosheduminer** [comment]
The authority there is not the certificate authority, it is actually the host. For example, in the case of github, "github.com" is the authority, while http or https would be the scheme.

**Comment by AlvinKuruvilla** [comment]
Oh I see, will address that now.. I'm planning on using a similar solution proposed for #2 to emulate the idea of having it as HTTP or HTTPS (but that will just be for the authority), etc 

Honestly I am probably overcomplicating it but I will probably refactor this later
