### ISSUE TITLE
Transfer the repository to the SirixDB organization

### ISSUE THREAD

**Issue by JohannesLichtenberger** [AlvinKuruvilla/Sirix-Go#3]
Hello,

we could transfer the repo to our origanization, such that all clients are together in one place. Of course you would get all rights as well as you can choose the license and so on :+1: 

kind regards
Johannes

**Comment by AlvinKuruvilla** [comment]
Sounds good @JohannesLichtenberger

**Comment by AlvinKuruvilla** [comment]
Let me know if there is anything I need to do to facilitate the process

**Comment by JohannesLichtenberger** [comment]
I created the repo and invited you :-)

**Comment by AlvinKuruvilla** [comment]
Hey I'm sorry can you sent the invitation again, it got lost in my inbox, and when I found it, it had already expired

**Comment by JohannesLichtenberger** [comment]
Done :-)

**Comment by AlvinKuruvilla** [comment]
Okay, I accepted the invitation. Quick question, do I just make a new branch of the repo and make a PR to commit to the repository, or is there another way?

**Comment by JohannesLichtenberger** [comment]
I think you can also transfer your repo or you simply commit/push your stuff to the new repo :-)

**Comment by AlvinKuruvilla** [comment]
Okay pushed my most recent changes to the new Github repo.. I have a local copy of that version of the repository anytime I want to push to the sirix repo I will just update the files and then push it
